### ISSUE TITLE
markdown library not compatible with WP repo?

### ISSUE THREAD

**Issue by swergroup** [markjaquith/WordPress-Plugin-Readme-Parser#2]
Hi Mark! 
We had an issue including this parser in a plugin we're submitting to the WordPress repository, because of this code section in the markdown library (137:139):

``` php
$mdwp_placeholders = explode(' ', str_rot13(
     'pEj07ZbbBZ U1kqgh4w4p pre2zmeN6K QTi31t9pre ol0MP1jzJR '.
     'ML5IjmbRol ulANi1NsGY J7zRLJqPul liA8ctl16T K9nhooUHli'));
```

It appears to be a third-party library, so I thought you'd like to know about this issue. 
Thank you for your code anyway!

**Comment by markjaquith** [comment]
Hm. Probably because it looks like suspicious obfuscation. Maybe just edit it to include the output of that `str_rot13` call: 

> cRw07MooOM H1xdtu4j4c cer2mzrA6X DGv31g9cer by0ZC1wmWE ZY5VwzoEby hyNAv1AfTL W7mEYWdChy yvN8pgy16G X9aubbHUyv
